name: 🚀 Feature request
description: Suggest an idea for 'Take you there'! 💡
title: "Feature: "
labels: [👀 needs triage, 💡 feature]
body:
  - type: markdown
    attributes:
      value: |
        Hello, stranger! Thank you for taking the time to fill out this feature request!
  - type: textarea
    attributes:
      label: Current behavior
      description: Is your feature request related to a problem? Please describe.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Suggested solution
      description: Describe the solution you'd like me to implement.
  - type: input
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem or helpful links here.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/JuditKaramazov/TakeYouThere/blob/main/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: checkboxes
    id: contribution
    attributes:
      label: Contributing Docs
      description: If you plan on contributing, please read our [Contribution Guide](https://github.com/JuditKaramazov/TakeYouThere/blob/main/CONTRIBUTING.md) first.
      options:
        - label: I agree to follow this project's Contribution Docs
          required: false